# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.hl7v2.fr.teleradiologie
canonical: https://interop.esante.gouv.fr/ig/hl7v2/teleradiologie # the last part of canonical and id must be the same
name: CISIS_TLR_HL7_V2 # Should be an acronym
title: Volet Téléradiologie
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: "Volume 1 : Etude fonctionnelle"
    norme_standard.md:
        title: Normes et Standards
    specifications_techniques.md:
        title: "Volume 2 : Détail des transactions"
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    change-log.md:
        title: Historique des versions
menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: specifications_fonctionnelles.html
    Normes et Standards: norme_standard.html
    Volume 2 – Détail des Transactions: specifications_techniques.html
    Volume 3 - Annexes:
        "Exemples de messages": exemples.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
